spring.application.name=order
server.port:8081
spring.datasource.url=jdbc:postgresql://localhost:5433/order-ms
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.addresses=amqp://localhost:5672