spring.application.name=processing
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/processing-ms
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.addresses=amqp://localhost:5672
